/**
 * Job: agent:generate-briefing
 *
 * When triggered from the web app, this job:
 * 1. Fetches the project and change request context
 * 2. Builds the developer briefing via shared buildDeveloperBriefing()
 * 3. Saves the AgentRun record in the DB
 * 4. Future: push to GitHub Issues, call an AI API, etc.
 */
import { prisma } from "@/lib/db";
import { AgentRunStatus } from "@prisma/client";
import type { AgentBriefingJobData } from "@/lib/queue";
import { logger } from "@/lib/logger";
import { buildDeveloperBriefing } from "@/lib/briefing";

export async function processAgentBriefing(data: AgentBriefingJobData) {
  const { projectId, changeRequestId, actorUserId } = data;

  const project = await prisma.projectWorkspace.findUnique({
    where: { id: projectId },
    include: {
      client: { select: { companyName: true } },
      repositories: true,
    },
  });

  if (!project) {
    throw new Error(`Project not found: ${projectId}`);
  }

  let changeRequest = null;
  if (changeRequestId) {
    changeRequest = await prisma.changeRequest.findUnique({
      where: { id: changeRequestId },
      select: {
        title: true,
        description: true,
        impact: true,
        sourceType: true,
      },
    });
  }

  const briefing = buildDeveloperBriefing(project, changeRequest);

  // Save the run record
  const agentRun = await prisma.agentRun.create({
    data: {
      projectId,
      changeRequestId: changeRequestId ?? null,
      initiatedByUserId: actorUserId,
      provider: "internal-worker",
      status: AgentRunStatus.COMPLETED,
      promptSnapshot: briefing,
      outputSummary: "Briefing generated by background worker",
    },
  });

  // Future hooks:
  // - await pushToGitHubIssue(briefing, primaryRepo)
  // - await callAiApi(briefing)
  // - await sendSlackNotification(...)

  logger.info("Briefing saved as AgentRun", { agentRunId: agentRun.id, projectId });
  return { agentRunId: agentRun.id };
}
